name: pack

on:
  release:
    types: [published, edited]
    branches: main
    tags: [ v* ]
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup folders
        run: |
          cd ${{ github.workspace }}
          sudo mkdir -p /cpthing_hard_set/bin/x64/plugins/cyber_engine_tweaks/mods/cpthing_hard_set/
      - name: Copy files
        run: |
          sudo cp -r CETKit /cpthing_hard_set/bin/x64/plugins/cyber_engine_tweaks/mods/cpthing_hard_set/
          sudo cp -r TeslaCoiled /cpthing_hard_set/bin/x64/plugins/cyber_engine_tweaks/mods/cpthing_hard_set/
          sudo cp HardSet.lua /cpthing_hard_set/bin/x64/plugins/cyber_engine_tweaks/mods/cpthing_hard_set/
          sudo cp HardSetDefaults.lua /cpthing_hard_set/bin/x64/plugins/cyber_engine_tweaks/mods/cpthing_hard_set/
          sudo cp Init.lua /cpthing_hard_set/bin/x64/plugins/cyber_engine_tweaks/mods/cpthing_hard_set/
          sudo cp LICENSE /cpthing_hard_set/bin/x64/plugins/cyber_engine_tweaks/mods/cpthing_hard_set/
          sudo cp README.md /cpthing_hard_set/bin/x64/plugins/cyber_engine_tweaks/mods/cpthing_hard_set/

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
            name: cpthing_hard_set-${{ github.ref_name }}.zip
            path: /cpthing_hard_set/
